apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
  namespace: argocd
spec:
  template:
    spec:
      initContainers:
        - name: argocd-extension-installer-argo-rollouts
          image: quay.io/argoprojlabs/argocd-extension-installer:v1.1.0@sha256:6cc786ba4dc96ba81d5010fbf92adabef15aff89753a55e22b8d829cd8b6e2a8
          env:
            - name: EXTENSION_NAME
              value: argo-rollouts-installer
            - name: EXTENSION_VERSION
              value: v0.2.5
            - name: EXTENSION_URL
              value: https://github.com/rodrigogeromin/argocd-system-ui-extension/releases/download/v0.2.5/argo-rollouts-installer.tar.gz
            - name: EXTENSION_CHECKSUM_URL
              value: https://github.com/rodrigogeromin/argocd-system-ui-extension/releases/download/v0.2.5/checksums.txt
            - name: EXTENSIONS_DIR
              value: /tmp/extensions/resources
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: [ALL]
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 200m
              memory: 128Mi
      containers:
        - name: argocd-server
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
